version: "3.7"
services:
  app:
    build:
      args:
        user: connectpluguser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravelimage
    container_name: connectplug-teste-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - connectplug-teste
  db:
    image: library/mysql:8.0.23
    container_name: connectplug-teste-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - connectplug-teste-db-vol:/var/lib/mysql
    networks:
      - connectplug-teste
  nginx:
    image: nginx:1.17-alpine
    container_name: connectplug-teste-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - connectplug-teste
  redis:
    image: redis:6.0.6-alpine
    container_name: connectplug-teste-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - connectplug-teste
volumes:
  connectplug-teste-db-vol:
networks:
  connectplug-teste:
    driver: bridge
